/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datum_desafio.app;

import datum_desafio.list.LinkedList;

import static datum_desafio.utilities.StringUtils.join;
import static datum_desafio.utilities.StringUtils.split;
import static datum_desafio.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
